{
        "apikeys": {
                "i0mf0rmer034": {
                        "app_key": "pgplvZFXMYtx494iQD2UhXwat",
                        "app_secret": "9dzDzuXmvyKfwQCspBTE6FBRiMmvN2MB3TytcPFpUa1olxdkMu",
                        "oauth_token": " 984036369688354816zZjZo2nFvh1XsWNORuS4NdAQturWFzl",
                        "oauth_token_secret": "vxNnvyY3ijBToVMwTowJiHZ4soNcuuRq66CgUGHr3AL4E"
                }
        }
}
